import{CONFIG,POWERS,SHOP}from'./config.js';
export const freshSave=()=>({name:'Ariel',coins:0,best:0,scores:[],owned:['lime','carbon','original'],equipped:{led:'lime',body:'carbon',skin:'original'},settings:{sound:true,haptic:true,sensitivity:1},daily:{date:'',distance:0,coins:0,powers:0,claimed:[]}});
export function readSave(storage=localStorage){try{let s=JSON.parse(storage.getItem('ariel-volt-v1'));if(!s)return freshSave();let f=freshSave();return{...f,...s,owned:Array.isArray(s.owned)?s.owned:f.owned,scores:Array.isArray(s.scores)?s.scores:[],equipped:{...f.equipped,...s.equipped},settings:{...f.settings,...s.settings},daily:{...f.daily,...s.daily}};}catch{return freshSave();}}
export function refreshDaily(save){let d=new Date(),date=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;if(save.daily.date!==date)save.daily={date,distance:0,coins:0,powers:0,claimed:[]};}
export const MISSIONS=[{id:'distance',name:'De punta a punta',label:'Recorre 1.500 m',target:1500,reward:120},{id:'coins',name:'Calderilla eléctrica',label:'Recoge 60 monedas',target:60,reward:100},{id:'powers',name:'Dale corriente',label:'Usa 5 potenciadores',target:5,reward:80}];
export function purchase(save,id){let item=SHOP.find(x=>x.id===id);if(!item)return false;if(!save.owned.includes(id)){if(save.coins<item.price)return false;save.coins-=item.price;save.owned.push(id);}save.equipped[item.kind]=id;return true;}
export class Run{
 constructor(random=Math.random){this.random=random;this.reset();}
 reset(){Object.assign(this,{time:0,distance:0,score:0,coins:0,battery:100,speed:CONFIG.startSpeed,lane:1,x:0,jump:0,slide:0,trick:0,tricks:0,trickBoost:0,lastJump:-99,powerUses:0,powers:{},objects:[],nextRow:45,nextPower:70,nextId:1,over:false,rain:false,events:[]});}
 emit(type,data={}){this.events.push({type,...data});}
 move(direction){if(this.over)return;let old=this.lane;this.lane=Math.max(0,Math.min(2,this.lane+direction));if(old!==this.lane&&this.jump>0&&this.time-this.lastJump<=CONFIG.trickWindow&&!this.trick){this.trick=.65;this.trickBoost=1.5;this.tricks++;this.score+=CONFIG.trickPoints;this.emit('trick');}}
 up(){if(this.over||this.jump>0||this.powers.drone)return;this.jump=CONFIG.jumpDuration;this.slide=0;this.lastJump=this.time;this.emit('jump');}
 down(){if(this.over||this.powers.drone)return;this.jump=0;this.slide=CONFIG.slideDuration;this.emit('slide');}
 get height(){return this.powers.drone?5:this.jump>0?Math.sin((1-this.jump/CONFIG.jumpDuration)*Math.PI)*CONFIG.jumpHeight:0;}
 activate(key){if(!POWERS[key])return;this.powers[key]=CONFIG.powerDuration;this.powerUses++;if(key==='turbo')this.battery=Math.min(100,this.battery+45);this.score+=50;this.emit('power',{key});}
 add(type,lane,z,key){this.objects.push({id:this.nextId++,type,lane,z,key,hit:false});}
 spawn(){while(this.distance+155>this.nextRow){let z=this.nextRow-this.distance,safe=Math.floor(this.random()*3),count=this.distance<150?1:2,blocked=[0,1,2].filter(n=>n!==safe);if(count===1)blocked=blocked.slice(0,1);blocked.forEach(l=>{let r=this.random();this.add(r<.28?'barrier':r<.52?'overhead':r<.78?'container':'bus',l,z);});for(let j=0;j<5;j++)this.add('coin',safe,z-5-j*2.5);if(this.random()<.22)this.add('charge',safe,z-21);this.nextRow+=Math.max(30,55-(this.distance/160))+this.random()*9;}
 while(this.distance+155>this.nextPower){let keys=Object.keys(POWERS),z=this.nextPower-this.distance,lane=Math.floor(this.random()*3);this.add('power',lane,z,keys[Math.floor(this.random()*keys.length)]);this.nextPower+=100+this.random()*45;}}
 update(dt){if(this.over)return;dt=Math.min(dt,.05);this.time+=dt;for(let k of['jump','slide','trick','trickBoost'])this[k]=Math.max(0,this[k]-dt);for(let k of Object.keys(this.powers)){this.powers[k]-=dt;if(this.powers[k]<=0)delete this.powers[k];}this.rain=this.distance%CONFIG.rainEvery>CONFIG.rainEvery-CONFIG.rainLength;this.battery=Math.max(0,this.battery-CONFIG.batteryDrain*dt);let base=Math.min(CONFIG.maxSpeed,CONFIG.startSpeed+this.time*CONFIG.acceleration);this.speed=this.powers.turbo?CONFIG.maxSpeed*1.25:Math.min(base,this.battery<=0?CONFIG.emptyBatteryMax:CONFIG.maxSpeed)+(this.trickBoost>0?4:0);let travel=this.speed*dt;this.distance+=travel;this.score+=travel*(this.powers.overclock?2:1);this.x+=(CONFIG.laneWidth*(this.lane-1)-this.x)*(1-Math.exp(-dt*(this.rain?7:14)));this.spawn();
 for(let o of this.objects){o.z-=travel;if(o.hit)continue;let dx=Math.abs((o.lane-1)*CONFIG.laneWidth-this.x),reach=o.type==='bus'?4.2:o.type==='container'?2.2:1.4,near=o.z<reach&&o.z>-reach,magnet=o.type==='coin'&&this.powers.magnet&&o.z<15&&o.z>-2;
 if(o.type==='coin'){if(magnet||(near&&dx<1.05)){o.hit=true;this.coins++;this.score+=CONFIG.coinPoints*(this.powers.overclock?2:1);this.emit('coin',{lane:o.lane});}continue;}
 if(!near||dx>.92)continue;if(o.type==='power'){o.hit=true;this.activate(o.key);continue;}if(o.type==='charge'){o.hit=true;this.battery=Math.min(100,this.battery+25);this.emit('charge');continue;}
 let clear=this.powers.drone||(o.type==='barrier'&&this.height>1.05)||(o.type==='overhead'&&this.slide>0);if(!clear){o.hit=true;if(this.powers.shield){delete this.powers.shield;this.emit('shield-break');}else{this.over=true;this.emit('crash');break;}}}
 this.objects=this.objects.filter(o=>o.z>-10&&!o.hit);}
}
